# Makefile

ROOT	= ../

include $(ROOT)Makefile.inc

#--------------------------------------------------------------------------

BUILD_TYPE	= lib

PROJECT	= libffc
TARGET	= $(LIB_DIR)$(PLATFORM)/$(CONFIG)/$(PROJECT).a

MODULES	= $(wildcard *.cpp)

INC_DIR	=

#--------------------------------------------------------------------------

include $(ROOT)Makefile.rules

#--------------------------------------------------------------------------
